# Generated by Django 3.2.3 on 2021-05-16 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='loaction',
            new_name='location',
        ),
    ]
